//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BrickController2.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TranslationResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TranslationResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BrickController2.Resources.TranslationResources", typeof(TranslationResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General settings.
        /// </summary>
        internal static string _defaultGroup {
            get {
                return ResourceManager.GetString("_defaultGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activate shelf mode.
        /// </summary>
        internal static string ActivateShelfMode {
            get {
                return ResourceManager.GetString("ActivateShelfMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to active the shelf mode for this BuWizz device? This will disconnect the battery from the device and typically requires the user to connect the charger in order to wake-up the device..
        /// </summary>
        internal static string ActivateShelfModeConfirm {
            get {
                return ResourceManager.GetString("ActivateShelfModeConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activation of the shelf mode has failed:.
        /// </summary>
        internal static string ActivateShelfModeFailed {
            get {
                return ResourceManager.GetString("ActivateShelfModeFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a new controller event.
        /// </summary>
        internal static string AddControllerEvent {
            get {
                return ResourceManager.GetString("AddControllerEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a new controller event for specific game controller.
        /// </summary>
        internal static string AddControllerEventForSpecificControllerId {
            get {
                return ResourceManager.GetString("AddControllerEventForSpecificControllerId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add controller events.
        /// </summary>
        internal static string AddControllerEvents {
            get {
                return ResourceManager.GetString("AddControllerEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a new controller profile.
        /// </summary>
        internal static string AddControllerProfile {
            get {
                return ResourceManager.GetString("AddControllerProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add controller profiles.
        /// </summary>
        internal static string AddControllerProfiles {
            get {
                return ResourceManager.GetString("AddControllerProfiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a new control point.
        /// </summary>
        internal static string AddControlPoint {
            get {
                return ResourceManager.GetString("AddControlPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add control points.
        /// </summary>
        internal static string AddControlPoints {
            get {
                return ResourceManager.GetString("AddControlPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a new creation.
        /// </summary>
        internal static string AddCreation {
            get {
                return ResourceManager.GetString("AddCreation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add creations.
        /// </summary>
        internal static string AddCreations {
            get {
                return ResourceManager.GetString("AddCreations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add device.
        /// </summary>
        internal static string AddDevice {
            get {
                return ResourceManager.GetString("AddDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manually add devices.
        /// </summary>
        internal static string AddDevicesManually {
            get {
                return ResourceManager.GetString("AddDevicesManually", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        internal static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a new sequence.
        /// </summary>
        internal static string AddSequence {
            get {
                return ResourceManager.GetString("AddSequence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add sequences.
        /// </summary>
        internal static string AddSequences {
            get {
                return ResourceManager.GetString("AddSequences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced settings.
        /// </summary>
        internal static string AdvancedSettings {
            get {
                return ResourceManager.GetString("AdvancedSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply changes.
        /// </summary>
        internal static string ApplyChanges {
            get {
                return ResourceManager.GetString("ApplyChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applying....
        /// </summary>
        internal static string Applying {
            get {
                return ResourceManager.GetString("Applying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to delete this controller action?.
        /// </summary>
        internal static string AreYouSureToDeleteControllerAction {
            get {
                return ResourceManager.GetString("AreYouSureToDeleteControllerAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to delete controller event.
        /// </summary>
        internal static string AreYouSureToDeleteControllerEvent {
            get {
                return ResourceManager.GetString("AreYouSureToDeleteControllerEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to delete this control point?.
        /// </summary>
        internal static string AreYouSureToDeleteControlPoint {
            get {
                return ResourceManager.GetString("AreYouSureToDeleteControlPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to delete creation.
        /// </summary>
        internal static string AreYouSureToDeleteCreation {
            get {
                return ResourceManager.GetString("AreYouSureToDeleteCreation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to delete device.
        /// </summary>
        internal static string AreYouSureToDeleteDevice {
            get {
                return ResourceManager.GetString("AreYouSureToDeleteDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to delete profile.
        /// </summary>
        internal static string AreYouSureToDeleteProfile {
            get {
                return ResourceManager.GetString("AreYouSureToDeleteProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to delete sequence.
        /// </summary>
        internal static string AreYouSureToDeleteSequence {
            get {
                return ResourceManager.GetString("AreYouSureToDeleteSequence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to delete this controller action?.
        /// </summary>
        internal static string AreYouSureToDeleteThisControllerAcrion {
            get {
                return ResourceManager.GetString("AreYouSureToDeleteThisControllerAcrion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto calibrate.
        /// </summary>
        internal static string AutoCalibrate {
            get {
                return ResourceManager.GetString("AutoCalibrate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Joy active zone.
        /// </summary>
        internal static string AxisActiveZone {
            get {
                return ResourceManager.GetString("AxisActiveZone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Joy characteristic.
        /// </summary>
        internal static string AxisCharacteristic {
            get {
                return ResourceManager.GetString("AxisCharacteristic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Joy dead zone.
        /// </summary>
        internal static string AxisDeadZone {
            get {
                return ResourceManager.GetString("AxisDeadZone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Joy type.
        /// </summary>
        internal static string AxisType {
            get {
                return ResourceManager.GetString("AxisType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base angle.
        /// </summary>
        internal static string BaseAngle {
            get {
                return ResourceManager.GetString("BaseAngle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Battery.
        /// </summary>
        internal static string Battery {
            get {
                return ResourceManager.GetString("Battery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blue.
        /// </summary>
        internal static string Blue {
            get {
                return ResourceManager.GetString("Blue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bluetooth devices will NOT be available.
        /// </summary>
        internal static string BluetoothDevicesWillNOTBeAvailable {
            get {
                return ResourceManager.GetString("BluetoothDevicesWillNOTBeAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bluetooth is turned off..
        /// </summary>
        internal static string BluetoothIsTurnedOff {
            get {
                return ResourceManager.GetString("BluetoothIsTurnedOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Button type.
        /// </summary>
        internal static string ButtonType {
            get {
                return ResourceManager.GetString("ButtonType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default output level.
        /// </summary>
        internal static string BuWizz2DefaultOutputLevel {
            get {
                return ResourceManager.GetString("BuWizz2DefaultOutputLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BuWizz 2 output level.
        /// </summary>
        internal static string BuWizz2OutputLevel {
            get {
                return ResourceManager.GetString("BuWizz2OutputLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swap channels.
        /// </summary>
        internal static string BuWizz2SwapChannels {
            get {
                return ResourceManager.GetString("BuWizz2SwapChannels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        internal static string BuWizz3Channel0 {
            get {
                return ResourceManager.GetString("BuWizz3Channel0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.
        /// </summary>
        internal static string BuWizz3Channel1 {
            get {
                return ResourceManager.GetString("BuWizz3Channel1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3.
        /// </summary>
        internal static string BuWizz3Channel2 {
            get {
                return ResourceManager.GetString("BuWizz3Channel2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4.
        /// </summary>
        internal static string BuWizz3Channel3 {
            get {
                return ResourceManager.GetString("BuWizz3Channel3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A.
        /// </summary>
        internal static string BuWizz3ChannelA {
            get {
                return ResourceManager.GetString("BuWizz3ChannelA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B.
        /// </summary>
        internal static string BuWizz3ChannelB {
            get {
                return ResourceManager.GetString("BuWizz3ChannelB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current limits for PU channels (mA).
        /// </summary>
        internal static string BuWizz3CurentLimitPoweredUp {
            get {
                return ResourceManager.GetString("BuWizz3CurentLimitPoweredUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current limits for PF channels (mA).
        /// </summary>
        internal static string BuWizz3CurentLimitPowerFunctions {
            get {
                return ResourceManager.GetString("BuWizz3CurentLimitPowerFunctions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default output level.
        /// </summary>
        internal static string BuWizzDefaultOutputLevel {
            get {
                return ResourceManager.GetString("BuWizzDefaultOutputLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BuWizz output level.
        /// </summary>
        internal static string BuWizzOutputLevel {
            get {
                return ResourceManager.GetString("BuWizzOutputLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calibrating....
        /// </summary>
        internal static string Calibrating {
            get {
                return ResourceManager.GetString("Calibrating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Channel setup.
        /// </summary>
        internal static string ChannelSetup {
            get {
                return ResourceManager.GetString("ChannelSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Channel type.
        /// </summary>
        internal static string ChannelType {
            get {
                return ResourceManager.GetString("ChannelType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a JSON file to import.
        /// </summary>
        internal static string ChooseJsonFileToImport {
            get {
                return ResourceManager.GetString("ChooseJsonFileToImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        internal static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting.
        /// </summary>
        internal static string Connecting {
            get {
                return ResourceManager.GetString("Connecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting to: .
        /// </summary>
        internal static string ConnectingTo {
            get {
                return ResourceManager.GetString("ConnectingTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controller.
        /// </summary>
        internal static string Controller {
            get {
                return ResourceManager.GetString("Controller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controller Action.
        /// </summary>
        internal static string ControllerAction {
            get {
                return ResourceManager.GetString("ControllerAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controller profile.
        /// </summary>
        internal static string ControllerProfile {
            get {
                return ResourceManager.GetString("ControllerProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control point.
        /// </summary>
        internal static string ControlPoint {
            get {
                return ResourceManager.GetString("ControlPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        internal static string Copy {
            get {
                return ResourceManager.GetString("Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy the controller profile to clipboard.
        /// </summary>
        internal static string CopyControllerProfile {
            get {
                return ResourceManager.GetString("CopyControllerProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy the creation to clipboard.
        /// </summary>
        internal static string CopyCreation {
            get {
                return ResourceManager.GetString("CopyCreation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy the sequence to clipboard.
        /// </summary>
        internal static string CopySequence {
            get {
                return ResourceManager.GetString("CopySequence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        internal static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating....
        /// </summary>
        internal static string Creating {
            get {
                return ResourceManager.GetString("Creating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creation.
        /// </summary>
        internal static string Creation {
            get {
                return ResourceManager.GetString("Creation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creation name.
        /// </summary>
        internal static string CreationName {
            get {
                return ResourceManager.GetString("CreationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creation name can not be empty.
        /// </summary>
        internal static string CreationNameCanNotBeEmpty {
            get {
                return ResourceManager.GetString("CreationNameCanNotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creations.
        /// </summary>
        internal static string Creations {
            get {
                return ResourceManager.GetString("Creations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark.
        /// </summary>
        internal static string Dark {
            get {
                return ResourceManager.GetString("Dark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default profile.
        /// </summary>
        internal static string DefaultProfile {
            get {
                return ResourceManager.GetString("DefaultProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting....
        /// </summary>
        internal static string Deleting {
            get {
                return ResourceManager.GetString("Deleting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device.
        /// </summary>
        internal static string Device {
            get {
                return ResourceManager.GetString("Device", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device name.
        /// </summary>
        internal static string DeviceName {
            get {
                return ResourceManager.GetString("DeviceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device name can not be empty..
        /// </summary>
        internal static string DeviceNameCanNotBeEmpty {
            get {
                return ResourceManager.GetString("DeviceNameCanNotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Devices.
        /// </summary>
        internal static string Devices {
            get {
                return ResourceManager.GetString("Devices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device settings.
        /// </summary>
        internal static string DeviceSettings {
            get {
                return ResourceManager.GetString("DeviceSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device type.
        /// </summary>
        internal static string DeviceType {
            get {
                return ResourceManager.GetString("DeviceType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disclaimer.
        /// </summary>
        internal static string Disclaimer {
            get {
                return ResourceManager.GetString("Disclaimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnecting.
        /// </summary>
        internal static string Disconnecting {
            get {
                return ResourceManager.GetString("Disconnecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to overwrite it?.
        /// </summary>
        internal static string DoYouWantToOverWrite {
            get {
                return ResourceManager.GetString("DoYouWantToOverWrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration (ms).
        /// </summary>
        internal static string DurationMs {
            get {
                return ResourceManager.GetString("DurationMs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the control point duration between 300 and 10000 ms..
        /// </summary>
        internal static string EnterControlPointDuration {
            get {
                return ResourceManager.GetString("EnterControlPointDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a creation name.
        /// </summary>
        internal static string EnterCreationName {
            get {
                return ResourceManager.GetString("EnterCreationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a device name.
        /// </summary>
        internal static string EnterDeviceName {
            get {
                return ResourceManager.GetString("EnterDeviceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a new profile name.
        /// </summary>
        internal static string EnterProfileName {
            get {
                return ResourceManager.GetString("EnterProfileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a sequence name.
        /// </summary>
        internal static string EnterSequenceName {
            get {
                return ResourceManager.GetString("EnterSequenceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error during scanning.
        /// </summary>
        internal static string ErrorDuringScanning {
            get {
                return ResourceManager.GetString("ErrorDuringScanning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export the controller profile.
        /// </summary>
        internal static string ExportControllerProfile {
            get {
                return ResourceManager.GetString("ExportControllerProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export the creation.
        /// </summary>
        internal static string ExportCreation {
            get {
                return ResourceManager.GetString("ExportCreation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export the sequence.
        /// </summary>
        internal static string ExportSequence {
            get {
                return ResourceManager.GetString("ExportSequence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export successful:.
        /// </summary>
        internal static string ExportSuccessful {
            get {
                return ResourceManager.GetString("ExportSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3rd party components.
        /// </summary>
        internal static string ExternalLibraries {
            get {
                return ResourceManager.GetString("ExternalLibraries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to connect..
        /// </summary>
        internal static string FailedToConnect {
            get {
                return ResourceManager.GetString("FailedToConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to export the controller profile..
        /// </summary>
        internal static string FailedToExportControllerProfile {
            get {
                return ResourceManager.GetString("FailedToExportControllerProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to export the creation..
        /// </summary>
        internal static string FailedToExportCreation {
            get {
                return ResourceManager.GetString("FailedToExportCreation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to export the sequence..
        /// </summary>
        internal static string FailedToExportSequence {
            get {
                return ResourceManager.GetString("FailedToExportSequence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to import the controller profile..
        /// </summary>
        internal static string FailedToImportControllerProfile {
            get {
                return ResourceManager.GetString("FailedToImportControllerProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to import the creation..
        /// </summary>
        internal static string FailedToImportCreation {
            get {
                return ResourceManager.GetString("FailedToImportCreation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to import the sequence..
        /// </summary>
        internal static string FailedToImportSequence {
            get {
                return ResourceManager.GetString("FailedToImportSequence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File already exits.
        /// </summary>
        internal static string FileAlreadyExists {
            get {
                return ResourceManager.GetString("FileAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icon set.
        /// </summary>
        internal static string IconSet {
            get {
                return ResourceManager.GetString("IconSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import a controller profile.
        /// </summary>
        internal static string ImportControllerProfile {
            get {
                return ResourceManager.GetString("ImportControllerProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import a creation.
        /// </summary>
        internal static string ImportCreation {
            get {
                return ResourceManager.GetString("ImportCreation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import a creation from file.
        /// </summary>
        internal static string ImportCreationFromFile {
            get {
                return ResourceManager.GetString("ImportCreationFromFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import a sequence.
        /// </summary>
        internal static string ImportSequence {
            get {
                return ResourceManager.GetString("ImportSequence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import a sequence from file.
        /// </summary>
        internal static string ImportSequenceFromFile {
            get {
                return ResourceManager.GetString("ImportSequenceFromFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import successful:.
        /// </summary>
        internal static string ImportSuccessful {
            get {
                return ResourceManager.GetString("ImportSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        internal static string Information {
            get {
                return ResourceManager.GetString("Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input device.
        /// </summary>
        internal static string InputDevice {
            get {
                return ResourceManager.GetString("InputDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input devices.
        /// </summary>
        internal static string InputDevices {
            get {
                return ResourceManager.GetString("InputDevices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input device tester.
        /// </summary>
        internal static string InputDeviceTester {
            get {
                return ResourceManager.GetString("InputDeviceTester", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interpolate.
        /// </summary>
        internal static string Interpolate {
            get {
                return ResourceManager.GetString("Interpolate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inv.
        /// </summary>
        internal static string Inv {
            get {
                return ResourceManager.GetString("Inv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invert.
        /// </summary>
        internal static string Invert {
            get {
                return ResourceManager.GetString("Invert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light.
        /// </summary>
        internal static string Light {
            get {
                return ResourceManager.GetString("Light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        internal static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location permission is needed for accessing bluetooth.
        /// </summary>
        internal static string LocationPermissionIsNeeded {
            get {
                return ResourceManager.GetString("LocationPermissionIsNeeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loop.
        /// </summary>
        internal static string Loop {
            get {
                return ResourceManager.GetString("Loop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max output.
        /// </summary>
        internal static string MaxOutput {
            get {
                return ResourceManager.GetString("MaxOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing.
        /// </summary>
        internal static string Missing {
            get {
                return ResourceManager.GetString("Missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are missing devices in the creation setup..
        /// </summary>
        internal static string MissingDevices {
            get {
                return ResourceManager.GetString("MissingDevices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing sequence.
        /// </summary>
        internal static string MissingSequence {
            get {
                return ResourceManager.GetString("MissingSequence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no controller actions added to the creation..
        /// </summary>
        internal static string NoControllerActions {
            get {
                return ResourceManager.GetString("NoControllerActions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No creations to import..
        /// </summary>
        internal static string NoCreationsToImport {
            get {
                return ResourceManager.GetString("NoCreationsToImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No controller profiles to import..
        /// </summary>
        internal static string NoProfilesToImport {
            get {
                return ResourceManager.GetString("NoProfilesToImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no sequences..
        /// </summary>
        internal static string NoSequences {
            get {
                return ResourceManager.GetString("NoSequences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No sequences to import..
        /// </summary>
        internal static string NoSequencesToImport {
            get {
                return ResourceManager.GetString("NoSequencesToImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off.
        /// </summary>
        internal static string Off {
            get {
                return ResourceManager.GetString("Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        internal static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On.
        /// </summary>
        internal static string On {
            get {
                return ResourceManager.GetString("On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manually add devices.
        /// </summary>
        internal static string OpenAddDevicesManually {
            get {
                return ResourceManager.GetString("OpenAddDevicesManually", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setup the channel.
        /// </summary>
        internal static string OpenChannelSetup {
            get {
                return ResourceManager.GetString("OpenChannelSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show the device details.
        /// </summary>
        internal static string OpenDeviceDetails {
            get {
                return ResourceManager.GetString("OpenDeviceDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit the sequence.
        /// </summary>
        internal static string OpenSequenceEditor {
            get {
                return ResourceManager.GetString("OpenSequenceEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output level.
        /// </summary>
        internal static string OutputLevel {
            get {
                return ResourceManager.GetString("OutputLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import a controller profile from clipboard.
        /// </summary>
        internal static string PasteControllerProfile {
            get {
                return ResourceManager.GetString("PasteControllerProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import a creation from clipboard.
        /// </summary>
        internal static string PasteCreation {
            get {
                return ResourceManager.GetString("PasteCreation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import a sequence from clipboard.
        /// </summary>
        internal static string PasteSequence {
            get {
                return ResourceManager.GetString("PasteSequence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permission request.
        /// </summary>
        internal static string PermissionRequest {
            get {
                return ResourceManager.GetString("PermissionRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play.
        /// </summary>
        internal static string Play {
            get {
                return ResourceManager.GetString("Play", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Easy drive mode (PLAYVM).
        /// </summary>
        internal static string PlayVmEnabled {
            get {
                return ResourceManager.GetString("PlayVmEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press a button or move a joy on the game controller.
        /// </summary>
        internal static string PressButtonOrMoveJoy {
            get {
                return ResourceManager.GetString("PressButtonOrMoveJoy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press buttons or move joys.
        /// </summary>
        internal static string PressButtonsOrMoveJoys {
            get {
                return ResourceManager.GetString("PressButtonsOrMoveJoys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press scan to discover devices.
        /// </summary>
        internal static string PressScanToDiscoverDevices {
            get {
                return ResourceManager.GetString("PressScanToDiscoverDevices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading and saving profiles will not be available..
        /// </summary>
        internal static string ProfileLoadSaveWillNotBeAvailable {
            get {
                return ResourceManager.GetString("ProfileLoadSaveWillNotBeAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile name.
        /// </summary>
        internal static string ProfileName {
            get {
                return ResourceManager.GetString("ProfileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile name can not be empty..
        /// </summary>
        internal static string ProfileNameCanNotBeEmpty {
            get {
                return ResourceManager.GetString("ProfileNameCanNotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Red.
        /// </summary>
        internal static string Red {
            get {
                return ResourceManager.GetString("Red", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename.
        /// </summary>
        internal static string Rename {
            get {
                return ResourceManager.GetString("Rename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renaming....
        /// </summary>
        internal static string Renaming {
            get {
                return ResourceManager.GetString("Renaming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        internal static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reseting....
        /// </summary>
        internal static string Reseting {
            get {
                return ResourceManager.GetString("Reseting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset settings to default.
        /// </summary>
        internal static string ResetToDefaults {
            get {
                return ResourceManager.GetString("ResetToDefaults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving....
        /// </summary>
        internal static string Saving {
            get {
                return ResourceManager.GetString("Saving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan for new devices.
        /// </summary>
        internal static string ScanForDevices {
            get {
                return ResourceManager.GetString("ScanForDevices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan for devices before adding controller events!.
        /// </summary>
        internal static string ScanForDevicesFirst {
            get {
                return ResourceManager.GetString("ScanForDevicesFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scanning....
        /// </summary>
        internal static string Scanning {
            get {
                return ResourceManager.GetString("Scanning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan QR code.
        /// </summary>
        internal static string ScanQr {
            get {
                return ResourceManager.GetString("ScanQr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searching for devices..
        /// </summary>
        internal static string SearchingForDevices {
            get {
                return ResourceManager.GetString("SearchingForDevices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select device.
        /// </summary>
        internal static string SelectDevice {
            get {
                return ResourceManager.GetString("SelectDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a device before saving..
        /// </summary>
        internal static string SelectDeviceBeforeSaving {
            get {
                return ResourceManager.GetString("SelectDeviceBeforeSaving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a sequence.
        /// </summary>
        internal static string SelectSequence {
            get {
                return ResourceManager.GetString("SelectSequence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sequence.
        /// </summary>
        internal static string Sequence {
            get {
                return ResourceManager.GetString("Sequence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sequence name.
        /// </summary>
        internal static string SequenceName {
            get {
                return ResourceManager.GetString("SequenceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sequence name can not be empty.
        /// </summary>
        internal static string SequenceNameCanNotBeEmpty {
            get {
                return ResourceManager.GetString("SequenceNameCanNotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This sequence name is already used.
        /// </summary>
        internal static string SequenceNameIsUsed {
            get {
                return ResourceManager.GetString("SequenceNameIsUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sequences.
        /// </summary>
        internal static string Sequences {
            get {
                return ResourceManager.GetString("Sequences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Servo range.
        /// </summary>
        internal static string ServoAngle {
            get {
                return ResourceManager.GetString("ServoAngle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share.
        /// </summary>
        internal static string Share {
            get {
                return ResourceManager.GetString("Share", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share the creation as file.
        /// </summary>
        internal static string ShareCreationAsFile {
            get {
                return ResourceManager.GetString("ShareCreationAsFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share the creation as text.
        /// </summary>
        internal static string ShareCreationAsText {
            get {
                return ResourceManager.GetString("ShareCreationAsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share the sequence as file.
        /// </summary>
        internal static string ShareSequenceAsFile {
            get {
                return ResourceManager.GetString("ShareSequenceAsFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share the sequence as text.
        /// </summary>
        internal static string ShareSequenceAsText {
            get {
                return ResourceManager.GetString("ShareSequenceAsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ch.
        /// </summary>
        internal static string ShortChannel {
            get {
                return ResourceManager.GetString("ShortChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step back.
        /// </summary>
        internal static string StepBack {
            get {
                return ResourceManager.GetString("StepBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next step.
        /// </summary>
        internal static string StepForward {
            get {
                return ResourceManager.GetString("StepForward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stepper angle.
        /// </summary>
        internal static string StepperAngle {
            get {
                return ResourceManager.GetString("StepperAngle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.
        /// </summary>
        internal static string System {
            get {
                return ResourceManager.GetString("System", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test the channel.
        /// </summary>
        internal static string TestDeviceChannel {
            get {
                return ResourceManager.GetString("TestDeviceChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme.
        /// </summary>
        internal static string Theme {
            get {
                return ResourceManager.GetString("Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn bluetooth on to connect to a bluetooth device..
        /// </summary>
        internal static string TurnOnBluetoothToConnect {
            get {
                return ResourceManager.GetString("TurnOnBluetoothToConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn bluetooth on to connect to bluetooth device(s)..
        /// </summary>
        internal static string TurnOnBluetoothToConnectBluetoothDevices {
            get {
                return ResourceManager.GetString("TurnOnBluetoothToConnectBluetoothDevices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        internal static string Value {
            get {
                return ResourceManager.GetString("Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value must be numeric..
        /// </summary>
        internal static string ValueMustBeNumeric {
            get {
                return ResourceManager.GetString("ValueMustBeNumeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value out of range..
        /// </summary>
        internal static string ValueOutOfRange {
            get {
                return ResourceManager.GetString("ValueOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value (%).
        /// </summary>
        internal static string ValuePercent {
            get {
                return ResourceManager.GetString("ValuePercent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        internal static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
