<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>BrickController2</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="UI\Images\*.png" />
  </ItemGroup>

  <ItemGroup>
    <!-- Custom Fonts -->
    <MauiFont Include="Resources\Fonts\*" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Autofac" />
    <PackageReference Include="Microsoft.Maui.Controls" />
    <PackageReference Include="Microsoft.Maui.Controls.Compatibility" />
    <PackageReference Include="Microsoft.Maui.Essentials" />
    <PackageReference Include="Newtonsoft.Json" />
    <PackageReference Include="sqlite-net-pcl" />
    <PackageReference Include="SQLiteNetExtensions" />
    <PackageReference Include="SQLiteNetExtensions.Async" />
    <PackageReference Include="SQLitePCLRaw.bundle_green" />
    <PackageReference Include="ZXing.Net.Maui.Controls" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="BrickController2.Tests" />
    <InternalsVisibleTo Include="DynamicProxyGenAssembly2" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Resources\TranslationResources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>TranslationResources.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Resources\TranslationResources.de.resx">
      <DependentUpon>TranslationResources.resx</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\TranslationResources.hu.resx">
      <DependentUpon>TranslationResources.resx</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\TranslationResources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>TranslationResources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <MauiXaml Update="UI\Controls\Devices\BoostChannelSelectorView.xaml">
      <Generator>MSBuild:Compile</Generator>
    </MauiXaml>
    <MauiXaml Update="UI\Controls\Devices\BuWizz3ChannelSelectorView.xaml">
      <Generator>MSBuild:Compile</Generator>
    </MauiXaml>
    <MauiXaml Update="UI\Controls\Devices\BuWizzChannelSelectorView.xaml">
      <Generator>MSBuild:Compile</Generator>
    </MauiXaml>
    <MauiXaml Update="UI\Controls\Devices\CaDARaceCarChannelSelectorView.xaml">
      <Generator>MSBuild:Compile</Generator>
    </MauiXaml>
    <MauiXaml Update="UI\Controls\Devices\CircuitCubesChannelSelectorView.xaml">
      <Generator>MSBuild:Compile</Generator>
    </MauiXaml>
    <MauiXaml Update="UI\Controls\Devices\DuploTrainHubChannelSelectorView.xaml">
      <Generator>MSBuild:Compile</Generator>
    </MauiXaml>
    <MauiXaml Update="UI\Controls\Devices\JieStarSCM4ChannelSelectorView.xaml">
      <Generator>MSBuild:Compile</Generator>
    </MauiXaml>
    <MauiXaml Update="UI\Controls\Devices\JieStarSCM8ChannelSelectorView.xaml">
      <Generator>MSBuild:Compile</Generator>
    </MauiXaml>
    <MauiXaml Update="UI\Controls\Devices\MK3_8ChannelSelectorView.xaml">
      <Generator>MSBuild:Compile</Generator>
    </MauiXaml>
    <MauiXaml Update="UI\Controls\Devices\MK4ChannelSelectorView.xaml">
      <Generator>MSBuild:Compile</Generator>
    </MauiXaml>
    <MauiXaml Update="UI\Controls\Devices\MK5ChannelSelectorView.xaml">
      <Generator>MSBuild:Compile</Generator>
    </MauiXaml>
    <MauiXaml Update="UI\Controls\Devices\MK6ChannelSelectorView.xaml">
      <Generator>MSBuild:Compile</Generator>
    </MauiXaml>
    <MauiXaml Update="UI\Controls\Devices\MK_DIYChannelSelectorView.xaml">
      <Generator>MSBuild:Compile</Generator>
    </MauiXaml>
    <MauiXaml Update="UI\Controls\Devices\PfxBrickChannelSelectorView.xaml">
      <Generator>MSBuild:Compile</Generator>
    </MauiXaml>
    <MauiXaml Update="UI\Controls\Devices\PoweredUpChannelSelectorView.xaml">
      <Generator>MSBuild:Compile</Generator>
    </MauiXaml>
    <MauiXaml Update="UI\Controls\Devices\PowerFunctionsChannelSelectorView.xaml">
      <Generator>MSBuild:Compile</Generator>
    </MauiXaml>
    <MauiXaml Update="UI\Controls\Devices\SBrickChannelSelectorView.xaml">
      <Generator>MSBuild:Compile</Generator>
    </MauiXaml>
    <MauiXaml Update="UI\Controls\Devices\SBrickLightChannelSelectorView.xaml">
      <Generator>MSBuild:Compile</Generator>
    </MauiXaml>
    <MauiXaml Update="UI\Controls\Devices\TechnicHubChannelSelectorView.xaml">
      <Generator>MSBuild:Compile</Generator>
    </MauiXaml>
    <MauiXaml Update="UI\Controls\Devices\TechnicMoveChannelSelectorView.xaml">
      <Generator>MSBuild:Compile</Generator>
    </MauiXaml>
    <MauiXaml Update="UI\Controls\Devices\WeDo2ChannelSelectorView.xaml">
      <Generator>MSBuild:Compile</Generator>
    </MauiXaml>
  </ItemGroup>
</Project>