name: Release BrickController WinUI 

on:
  push:
    branches:
      - default
      - 'release/**'
    paths:
      - '.github/**/*windows.yml'
      - '*.props'
      - '*.slnx'
      - 'BrickController2/BrickController2/**'
      - 'BrickController2/BrickController2.WinUI/**'
  release:
    types:
      - published
  workflow_dispatch:

permissions:
  contents: read

env:
  PROJECT_FOLDER: "BrickController2/BrickController2.WinUI"
  TARGET_RUNTIME: 'win-x64'

jobs:
  build-winui:
    runs-on: windows-2025
    name: BrickController WinUI Build

    steps:
    - uses: actions/checkout@v6
    - name: Setup MAUI
      id: setup-maui
      uses: ./.github/actions/setup-maui
      with:
        platform: windows10.0.19041.0
        workload-id: maui-windows

    - name: Find Current Release Info
      if: github.event_name == 'release' && github.event.action == 'published'
      id: get_release
      uses: octokit/request-action@v3.x
      with:
        route: GET /repos/${{ github.repository }}/releases/tags/${{ github.event.release.tag_name }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Decode Signing Certificate
      shell: pwsh
      run: |
        Set-Content -Path cert.asc -Value "${{ secrets.SIGNING_CERTIFICATE_BASE_64_CONTENT }}" -NoNewline -Encoding Ascii
        certutil -decode cert.asc cert.pfx

    - name: Install Signing Certificate
      run: certutil -user -p "${{ secrets.SIGNING_CERTIFICATE_PASSWORD }}" -Silent -importpfx cert.pfx NoRoot

    - name: Restore Dependencies
      run: dotnet restore ${{ env.PROJECT_FOLDER }}/BrickController2.WinUI.csproj

    - name: Build
      run: dotnet build ${{ env.PROJECT_FOLDER }}/BrickController2.WinUI.csproj `
        -c Release `
        -r ${{ env.TARGET_RUNTIME }} `
        -p:Platform=x64 `
        -p:ApplicationVersion="${{ github.run_number }}"

    - name: Build MAUI WinUI App
      run: dotnet publish ${{ env.PROJECT_FOLDER }}/BrickController2.WinUI.csproj `
        -c Release `
        -r ${{ env.TARGET_RUNTIME }} `
        -p:Platform=x64 `
        -p:GenerateAppxPackageOnBuild=true `
        -p:AppxPackageSigningEnabled=true `
        -p:PackageCertificateThumbprint=${{ secrets.SIGNING_CERTIFICATE_THUMBPRINT }}

    - name: Upload WinUI Artifact
      uses: actions/upload-artifact@v7
      with:
        name: brickcontroller-winui-ci-build
        path: ${{ env.PROJECT_FOLDER }}\AppPackages\**\BrickController*.msix
        retention-days: 14

    - name: Upload Artifact to Release
      if: github.event_name == 'release' && github.event.action == 'published'
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ fromJson(steps.get_release.outputs.data).upload_url }}
        asset_path: ${{ env.PROJECT_FOLDER }}\AppPackages\BrickController2.WinUI_${{ steps.setup-maui.outputs.app-version }}.${{github.run_number}}_Test\BrickController2.WinUI_${{ steps.setup-maui.outputs.app-version }}.${{github.run_number}}_x64.msix
        asset_name: BrickController2_${{ steps.setup-maui.outputs.app-version }}.msix
        asset_content_type: application/vnd.ms-appx
      env:
        GITHUB_TOKEN: ${{ secrets.CI_RELEASE_ASSETS_PAT }}
