name: Build iOS app

on:
  push:
    branches:    
      - main
      - '*'
    paths-ignore:
      - '**/*.md'
      - '**/*.gitignore'
      - '**/*.gitattributes'    
  pull_request:
    branches:    
      - main
      - '*'

jobs:
  build:

    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Setup .NET 8
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x
            
      - name: Install MAUI workload
        run: dotnet workload install maui

      - name: Restore Dependencies
        run: dotnet restore BrickController2/BrickController2.iOS/BrickController2.iOS.csproj

      - name: Import Code-Signing Certificates
        uses: Apple-Actions/import-codesign-certs@v2
        with:
          p12-file-base64: ${{ secrets.CERTIFICATES_P12 }}
          p12-password: ${{ secrets.CERTIFICATES_P12_PASSWORD }}

      - name: Download Apple Provisioning Profiles
        uses: Apple-Actions/download-provisioning-profiles@v1
        with:
          bundle-id: 'my.app.bundle.identifier'
          issuer-id: ${{ secrets.APPSTORE_ISSUER_ID }}
          api-key-id: ${{ secrets.APPSTORE_KEY_ID }}
          api-private-key: ${{ secrets.APPSTORE_PRIVATE_KEY }}          
          
      - name: Publish the iOS app
        run: dotnet publish BrickController2/BrickController2.iOS/BrickController2.iOS.csproj -c Release -f:net8.0-ios --no-restore /p:ArchiveOnBuild=true /p:EnableAssemblyILStripping=false

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.0.0
        with:
          path: '**/*.ipa'        
