name: Validation build BrickController WinUI 

on:
  pull_request:
    branches:    
      - default
      - 'release/**'
    paths:
      - '.github/**/*windows.yml'
      - '*.props'
      - '*.slnx'
      - 'BrickController2/BrickController2/**'
      - 'BrickController2/BrickController2.WinUI/**'
  workflow_dispatch:

permissions:
  contents: read

env:
  PROJECT_FOLDER: "BrickController2/BrickController2.WinUI"
  TARGET_RUNTIME: 'win-x64'

jobs:
  build-winui:
    runs-on: windows-2025
    name: BrickController WinUI Build

    steps:
    - uses: actions/checkout@v6
    - name: Setup MAUI
      id: setup-maui
      uses: ./.github/actions/setup-maui
      with:
        platform: windows10.0.19041.0
        workload-id: microsoft-net-sdk-windows

    - name: Restore Dependencies
      run: dotnet restore ${{ env.PROJECT_FOLDER }}/BrickController2.WinUI.csproj

    - name: Build
      run: dotnet build ${{ env.PROJECT_FOLDER }}/BrickController2.WinUI.csproj `
        -c Release `
        -r ${{ env.TARGET_RUNTIME }} `
        -p:Platform=x64 `
        -p:ApplicationVersion="${{ github.run_number }}"

    - name: Build MAUI WinUI App
      run: dotnet publish ${{ env.PROJECT_FOLDER }}/BrickController2.WinUI.csproj `
        -c Release `
        -r ${{ env.TARGET_RUNTIME }} `
        -p:Platform=x64 `
        -p:GenerateAppxPackageOnBuild=true `
        -p:AppxPackageSigningEnabled=false

    - name: Upload WinUI Artifact
      uses: actions/upload-artifact@v7
      with:
        name: brickcontroller-winui-ci-build
        path: .\**\AppPackages\**\BrickController*.msix
        retention-days: 5