name: Validation build BrickController Android

on:
  pull_request:
    branches:    
      - default
      - 'release/**'
    paths:
      - '.github/**/*android.yml'
      - '*.props'
      - '*.slnx'
      - 'BrickController2/BrickController2/**'
      - 'BrickController2/BrickController2.Android/**'
  workflow_dispatch:

permissions:
  contents: read

env:
  PROJECT_FOLDER: "BrickController2/BrickController2.Android"

jobs:
  build-android:
    runs-on: ubuntu-latest
    name: BrickController Android Build

    steps:
    - uses: actions/checkout@v6
    - name: Setup MAUI
      id: setup-maui
      uses: ./.github/actions/setup-maui
      with:
        platform: android

    - name: Restore Dependencies
      run: dotnet restore ${{ env.PROJECT_FOLDER }}/BrickController2.Android.csproj

    - name: Build MAUI Android (APK)
      run: >-
        dotnet publish ${{ env.PROJECT_FOLDER }}/BrickController2.Android.csproj
        -c Release
        -f ${{ steps.setup-maui.outputs.target-framework }}
        --no-restore
        -p:ApplicationVersion="${{ github.run_number }}"
        -p:AndroidPackageFormat=apk
        -p:AndroidKeyStore=false

    - name: Upload Android Artifact
      uses: actions/upload-artifact@v7
      with:
        name: brickcontroller-android-ci-build
        path: ${{ env.PROJECT_FOLDER }}/bin/Release/${{ steps.setup-maui.outputs.target-framework }}/*-Signed.apk
        retention-days: 5
