name: Build BrickController Android 

on:
  push:
    branches:
      - default
      - 'releases/**'
    paths:
      - '.github/**/*.yml'
      - 'BrickController2/*.props'
      - 'BrickController2/*.sln'
      - 'BrickController2/BrickController2/**'
      - 'BrickController2/BrickController2.Android/**'
  pull_request:
    branches:    
      - default
      - 'releases/**'
    paths:
      - '.github/**/*.yml'
      - 'BrickController2/*.props'
      - 'BrickController2/*.sln'
      - 'BrickController2/BrickController2/**'
      - 'BrickController2/BrickController2.Android/**'
  release:
    types:
      - published
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build-android:
    runs-on: windows-2025
    name: BrickController Android Build
    steps:

    - uses: octokit/request-action@v2.x
      id: get_latest_release
      with:
        route: GET /repos/${{ github.repository }}/releases/latest
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Debug Latest Release
      run: echo ${{ steps.get_latest_release.outputs.data }}

    - name: Debug Latest Release
      run: | 
          echo "username=${{ fromJson(steps.get_contribution_data.outputs.data)[0].user.login }}" >> $GITHUB_ENV
          echo "avatar_url=${{ fromJson(steps.get_contribution_data.outputs.data)[0].user.avatar_url }}" >> $GITHUB_ENV
          echo "commit_sha=${{ github.sha }}" >> $GITHUB_ENV
          echo "message=${{ fromJson(steps.get_contribution_data.outputs.data)[0].title }}" >> $GITHUB_ENV


    - name: Find Release ID
      #if: github.event_name == 'release' && github.event.action == 'published'
      id: get_release_test
      uses: octokit/request-action@v2.x
      with:
        route: GET /repos/${{ github.repository }}/releases/tags/2025.04.Beta1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Debug Release ID
      run: echo ${{ steps.get_release_test.outputs.upload_url }}

    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
            
    - name: Restore Dependencies
      run: dotnet restore BrickController2/BrickController2.Android/BrickController2.Android.csproj
    - name: Build MAUI Android
      run: dotnet publish BrickController2/BrickController2.Android/BrickController2.Android.csproj -c Release -f net9.0-android --no-restore

    - name: Upload Android Artifact
      uses: actions/upload-artifact@v4
      with:
        name: brickcontroller-android-ci-build
        path: BrickController2/BrickController2.Android/bin/Release/net9.0-android/com.scn.BrickController2-Signed.apk

    - name: Find Release ID
      #if: github.event_name == 'release' && github.event.action == 'published'
      id: get_release
      uses: octokit/request-action@v2.x
      with:
        route: GET /repos/${{ github.repository }}/releases/tags/2025.04.Beta1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload Artifact to Release
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.get_release.outputs.upload_url }}
        asset_path: BrickController2/BrickController2.Android/bin/Release/net9.0-android/com.scn.BrickController2-Signed.apk
        asset_name: com.scn.BrickController2-Signed.apk
        asset_content_type: application/vnd.android.package-archive
